<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="userData.aspx.cs" Inherits="Aviral_ASP.userData" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>APP | User Data</title>
    <link rel="stylesheet" type="text/css" href="content/styles.css" />
</head>
<body>

    <div class="container">
        <form id="form1" runat="server">
            <h2>User Details</h2>
            <div class="table-container">
                <asp:GridView ID="GridView1" runat="server" CssClass="table" AutoGenerateColumns="True"
                    DataKeyNames="ID" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"
                    OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating"
                    OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting">
                </asp:GridView>
            </div>

            <br />

            <div class="form-group">
                <div class="btnContainer">
                    <asp:Button ID="addData" runat="server" CssClass="btn" Text="Add Data" OnClick="addData_Click" />
                    <asp:Button ID="masterButton" runat="server" CssClass="btn" Text="Master Sheet" OnClick="masterData_Click" />
                </div>
            </div>
           

        </form>
    </div>

</body>
</html>